update dockerfile

diff --git a/elastio-ec2-backup_ecs_stopped_task/Dockerfile b/elastio-ec2-backup_ecs_stopped_task/Dockerfile
--- a/elastio-ec2-backup_ecs_stopped_task/Dockerfile
+++ b/elastio-ec2-backup_ecs_stopped_task/Dockerfile
@@ -4,14 +4,27 @@
 # Most likely this is not the latest version of elastio cli.
 # You can find the latest version at this link.
 # https://gallery.ecr.aws/elastio-dev/elastio-cli
-FROM public.ecr.aws/elastio-dev/elastio-cli:0.17.0-master
+FROM public.ecr.aws/elastio-dev/elastio-cli:latest
 
-RUN apt-get update && apt-get upgrade -y
-RUN apt-get install -y python3-pip python3
+RUN apt-get update
+RUN \
+    set -ex \
+    && apt-get install -y --no-install-suggests --no-install-recommends \
+        python3-pip python3
+
 COPY requirements.txt  ./
 RUN python3 -m pip install --no-cache-dir -r requirements.txt
+
 COPY failed_ecs_handler.py ./
 COPY failed_ecs_handler_config.py ./
 
-ENTRYPOINT [ ]
-CMD python3 failed_ecs_handler.py
+# Clean up
+RUN \
+   set -ex \
+   && apt-get purge python3-pip -y \
+   && apt-get autoremove -y \
+   && apt-get clean -y \
+   && rm -rf /var/lib/apt/lists/*
+
+ENTRYPOINT ["python3"]
+CMD ["failed_ecs_handler.py"]
